### ISSUE TITLE
Making releases doc has a few issues

### ISSUE THREAD

**Issue by mightyiam** [wymeditor/wymeditor#726]
* [x] After making pre-release changes, commit all of them, not just `dist`.
* [x] Release title should have no prefix `v`.
* [x] After release, bump to placeholder version string `next`
* [ ] Remove directive on pre–release changelog entry consolidation

**Comment by winhamwr** [comment]
> Do not bump the version string. Just append +dev suffix.

v1.0.0dev is before v1.0.0, not after.

From [semvar](http://semver.org/):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by winhamwr** [comment]
Also, the v1.0.0 changelog is not complete, right?

From the [docs](https://github.com/wymeditor/wymeditor/blob/master/docs/wymeditor_development/making_releases.rst#update-the-changelog):

If this release makes a transition from alpha to beta or from beta to stable, consolidate alpha/beta change–log entries in to a unified section for this release.
If this is a major release, highlight important changes.

The changelog should be everything someone upgrading from 0.5 should know about.

**Comment by mightyiam** [comment]
> v1.0.0dev is before v1.0.0, not after.

You're right.

> If this release makes a transition from alpha to beta or from beta to stable, consolidate alpha/beta change–log entries in to a unified section for this release.

I don't like this because this is rewriting history. I'll remove this directive, ok?

> If this is a major release, highlight important changes.

Perhaps in this release, because we did not adhere to semver, it is appropriate. For next releases, this isn't worth it.

I will update the changelog with the highlights and release `1.0.0+1`.

> The changelog should be everything someone upgrading from 0.5 should know about.

I don't like this. The entry for each release has a section with breaking changes. Each implementer may be upgrading from a different version. When they do, they know to account for the breaking changes in all of the appropriate releases.

**Comment by winhamwr** [comment]
> I don't like this because this is rewriting history. I'll remove this directive, ok?

Not OK with me. The purpose of a changelog is to be useful for the people doing upgrades. For people on 0.5.0, asking them to go through the incremental changelogs of ~15 pre-release versions is sadistic. Look at a project like Django, for example. They have minor changelogs between pre-release versions for folks that are installing those, but the bulk of the work is in the release => release changelog, which is largely a consolidation of the pre-release to pre-release changelogs. Does that make sense?

Or maybe you would prefer to make a new thing entirely called "release notes" that pulls in all of the information that someone would need to upgrade from 0.5.0 and to leave the changelog alone?

**Comment by mightyiam** [comment]
> Not OK with me. The purpose of a changelog is to be useful for the people doing upgrades. For people on 0.5.0, asking them to go through the incremental changelogs of ~15 pre-release versions is sadistic. Look at a project like Django, for example. They have minor changelogs between pre-release versions for folks that are installing those, but the bulk of the work is in the release => release changelog, which is largely a consolidation of the pre-release to pre-release changelogs. Does that make sense?

This is not Django. It will have far less changes between releases, from now on, right?

> Or maybe you would prefer to make a new thing entirely called "release notes" that pulls in all of the information that someone would need to upgrade from 0.5.0 and to leave the changelog alone?

For this release, release notes may be a good idea, although if I was implementing an upgrade, I would surely go over everything that is declared breaking in the relevant changelog entries.

What summary could ease that? What release notes other than "Many of you are probably on 0.5. When upgrading, please go over the relevant changelog entries (we know there is quite a few) and look for "breaking" or "backwards-incompatible" changes." can we make up, which will help?

Of course, I'm not talking about feature and improvement highlights.
